apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    team: app32
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
