apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
  annotations:
    container.apparmor.security.beta.kubernetes.io/sample-app: runtime/default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      volumes:
      - name: host-vol
        hostPath:
          path: /etc
      containers:
      - name: sample-app
        image: nginx:latest
        ports:
        - containerPort: 80
        securityContext:
          privileged: false
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
